export const types = {
    SET_USERS_DATA: "[USERS] SET DATA",
    EDIT_USER_DATA: "[USERS] EDIT DATA",
    SET_USERS_FILTERS: "[USERS] SET FILTERS",
    REMOVE_USERS_DATA: "[USERS] REMOVE DATA",
    SET_USERS_ERROR: "[USERS] SET ERROR",
    REMOVE_USERS_ERROR: "[USERS] REMOVE ERROR",
    SET_USERS_LOADING: "[USERS] SET LOADING",
};
